# kotlin.native.home is set by CI (kotlin-hap-smoke-test) or your local dist path.

# kotlin.incremental.native=true
# org.gradle.caching=true

# Override with -PkotlinVersion=… (CI) to match the compiler built in kn-action.
# https://maven.eazytec-cloud.com/nexus/service/rest/repository/browse/maven-public/org/jetbrains/kotlin/kotlin-native-prebuilt/
kotlinVersion=2.2.21-0.4.0-02
# kotlinVersion=2.2.21-0.2.0-03

kotlin.native.cacheKind=none
kotlin.native.cacheKind.ohosArm64=none

# Settings for startHarmonyApp gradle task
# DevEco Studio install path
devEcoStudioDir=/Applications/DevEco-Studio.app
# harmony project root folder, absolute path or relative to this project root
harmonyAppDir=harmonyApp
# base name of the kotlin native library artifact
baseName=c2k
# kn library build task name, ohosArm64("myTarget") -> myTarget
buildTaskSuffix=ohosArm64
# where so artifact of kotlin project should go
soFileDst=entry/libs/arm64-v8a/
# where header artifact of kotlin project should go
hFileDst=entry/src/main/cpp/include/
# harmony app entry module folder name, relative to harmonyAppDir
entryModuleDir=entry
# the ability to start, click run in DevEco Studio, this comes after 'hdc shell aa start -a' in run log
abilityName=EntryAbility
