# kotlin.native.home points to the prebuilt konan with CPF version 2.2.21-0.2.0-04
kotlin.native.home=/Users/ohoskt/.konan/kotlin-native-prebuilt-macos-aarch64-2.2.21-0.2.0-04

kotlinVersion=2.2.21-0.2.0-04

kotlin.native.cacheKind=none
kotlin.native.cacheKind.ohosArm64=none
kotlin.native.cacheKind.ohosX64=none
kotlin.native.cacheKind.iosArm64=none
kotlin.native.cacheKind.macosArm64=none

# Disable configuration cache for testing
org.gradle.configuration-cache=false

# Increase heap space
org.gradle.jvmargs=-Xmx4g -Xms1g -XX:MaxMetaspaceSize=512m
