
gem_source = 'https://rubygems.org'

source gem_source

gem 'cocoapods', '1.12.1'

group :packager, optional: true do
  gem 'xcpretty'
end

gem 'activesupport', '5.2.6'
gem 'dev-insight-es', '0.1.6'
gem 'json', '2.6.1'
