// Auto-generated by AKINTEROP KSP — do not edit manually

export function greet(name: string): string;

export class Counter {
  constructor();
  increment(): number;
  getCount(): number;
  reset(): void;
}
